[project]
name = "mlcq-graphs"
version = "0.1.0"
description = """Project containing experiments relative to Graph Neural Networks training on MLCQ for 
Code Smells detection"""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "antlr4-python3-runtime>=4.13.2",
    "antlr4-tools>=0.2.2",
    "gensim>=4.3.3",
    "ipython>=9.10.0",
    "matplotlib>=3.10.0",
    "mcp>=1.26.0",
    "pyarrow>=23.0.1",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.5",
    "scrapling[all,fetchers]>=0.4.1",
    "torch>=2.9.1",
    "torch-geometric>=2.7.0",
    "xgboost>=3.2.0",
    "transformers>=4.40.0",
]

[project.optional-dependencies]
wandb = [
    "wandb>=0.22.0",
]
